SELECT AUTHOR
FROM
  (SELECT LENGTH(title) + LENGTH(NEWS.NEWS_CONTENT) + LENGTH(NEWS.BRIEF) AS NEWS_CHARS,
    AUTHORS.NAME                                                         AS AUTHOR
  FROM (NEWS_AUTHORS
  JOIN NEWS
  ON NEWS = NEWS.NEWS_ID
  JOIN AUTHORS
  ON NEWS_AUTHORS.AUTHOR = AUTHORS.AUTHOR_ID)
  )
GROUP BY AUTHOR HAVING SUM(NEWS_CHARS) > 3000 AND AVG(NEWS_CHARS) > 500;